# Fancy Indexing

In [1]:
import numpy as np

In [2]:
pl = [ x for x in range(16)]
pl

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [3]:
nl = np.arange(16)
np.random.shuffle(nl)
nl

array([13, 15,  3,  1,  2, 12,  8,  0,  9, 11,  6,  5,  4, 10,  7, 14])

In [4]:
idx = [3, 5, 8]

In [5]:
nl[idx]

array([ 1, 12,  9])

In [6]:
idx2 = np.array([
    [0,2],
    [1,3]
])
idx2

array([[0, 2],
       [1, 3]])

In [7]:
nl[idx2]

array([[13,  3],
       [15,  1]])

In [8]:
nlXY = nl.reshape((4,-1))
nlXY

array([[13, 15,  3,  1],
       [ 2, 12,  8,  0],
       [ 9, 11,  6,  5],
       [ 4, 10,  7, 14]])

In [9]:
row = [0,1]
col = [1,2]
nlXY[row, col]

array([15,  8])

In [10]:
nlXY[0,col]

array([15,  3])

In [11]:
nlXY[:,col]

array([[15,  3],
       [12,  8],
       [11,  6],
       [10,  7]])

* 每个位置可以传入字数、切片、数组，两个位置都是数组且长度都大于1时，数组的长度需要一致

In [12]:
nlXY[:2,[True,False, True, True]]

array([[13,  3,  1],
       [ 2,  8,  0]])

## Numpy.array的比较

In [13]:
nl

array([13, 15,  3,  1,  2, 12,  8,  0,  9, 11,  6,  5,  4, 10,  7, 14])

In [14]:
nl<3

array([False, False, False,  True,  True, False, False,  True, False,
       False, False, False, False, False, False, False])

In [15]:
np.sum(nl<=4)

5

In [16]:
np.count_nonzero(nl<=4)

5

In [17]:
np.any(nl==0)

True

In [18]:
np.all(nl>0)

False

In [19]:
nlXY

array([[13, 15,  3,  1],
       [ 2, 12,  8,  0],
       [ 9, 11,  6,  5],
       [ 4, 10,  7, 14]])

In [20]:
np.sum(nlXY%2==0, axis=1)

array([0, 4, 1, 3])

In [21]:
np.sum((nl>3)&(nl<10))

6

In [23]:
np.sum(~(nl==0))

15

* 组合运算时函数体内需要用位运算符

In [22]:
nl[nl<=5]

array([3, 1, 2, 0, 5, 4])

In [26]:
nlXY

array([[13, 15,  3,  1],
       [ 2, 12,  8,  0],
       [ 9, 11,  6,  5],
       [ 4, 10,  7, 14]])

In [35]:
nlXY[(nlXY[:,-1]%5==0),:]

array([[ 2, 12,  8,  0],
       [ 9, 11,  6,  5]])