## 聚合操作和索引操作

## 聚合操作

In [1]:
import numpy as np

In [2]:
L = np.random.random(100)

In [3]:
L

array([0.9601174 , 0.81905846, 0.02621039, 0.16704334, 0.41761332,
       0.76005177, 0.31949934, 0.92969048, 0.68036948, 0.691797  ,
       0.43391812, 0.64518784, 0.44795249, 0.8442662 , 0.94570305,
       0.81572576, 0.89854736, 0.53918243, 0.93553648, 0.25082345,
       0.70390304, 0.19772667, 0.31762485, 0.97627292, 0.11757254,
       0.08091321, 0.94259415, 0.15047508, 0.82640932, 0.3964987 ,
       0.27557805, 0.94941945, 0.4678432 , 0.85625674, 0.11281891,
       0.8607057 , 0.95052498, 0.79967552, 0.217407  , 0.00448927,
       0.58132297, 0.53760895, 0.03315595, 0.95069193, 0.34211848,
       0.88108073, 0.06412024, 0.67569661, 0.5024652 , 0.40204514,
       0.32283492, 0.34309995, 0.43299856, 0.25088599, 0.01697613,
       0.98763975, 0.16221027, 0.46440336, 0.65537883, 0.10885653,
       0.84068066, 0.20592267, 0.34515181, 0.72561557, 0.15733806,
       0.4347599 , 0.14685025, 0.31777051, 0.69793252, 0.37977967,
       0.34061062, 0.3999959 , 0.45399978, 0.5953185 , 0.48791

In [7]:
np.sum(L)

49.58280170273385

In [10]:
big_array = np.random.random(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

198 ms ± 3.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.75 ms ± 21.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [14]:
x = np.arange(16).reshape((4, -1))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
np.sum(x)

120

In [19]:
sum(x)

array([24, 28, 32, 36])

In [20]:
np.sum(x, axis=0)

array([24, 28, 32, 36])

In [23]:
np.sum(x, axis=1)

array([ 6, 22, 38, 54])

In [24]:
np.prod(x+1)

2004189184

* mean:平均值

In [25]:
np.mean(x)

7.5

* median:中位数(排在数据中间的数，单个取值，两个平均)

In [26]:
np.median(x)

7.5

In [28]:
salary = np.array([1,1,2,2,10])

In [29]:
np.mean(salary)

3.2

In [30]:
np.median(salary)

2.0

* percentile:百分位，从小到大排列后，处于x%的数(如果中间没有数，则按中间两个数的远近比列取平均值)

In [31]:
np.percentile(big_array, 50)

0.49998474451206526

In [33]:
np.median(big_array)

0.49998474451206526

In [39]:
np.percentile(salary, 38)

1.52

* 方差

In [40]:
np.var(salary)

11.76

* 标准差

In [62]:
np.std(salary)

3.4292856398964493

In [61]:
normal_array = np.random.normal(10,10,1000)
print(np.mean(normal_array))
print(np.median(normal_array))
print(np.var(normal_array))
print(np.std(normal_array))

9.581039027106934
9.42315781989091
90.71313225388194
9.524344190225484


## 索引操作

In [64]:
p = np.random.normal(0,1,10000)
np.mean(p)

0.015325680570420507

In [65]:
np.min(p)

-4.203443687854901

In [66]:
np.argmin(p)

8161

In [68]:
p[8161]

-4.203443687854901

### 排序和使用索引(arg)

In [70]:
nf = np.arange(16)
nf

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [73]:
np.random.shuffle(nf)
nf

array([11,  1,  0,  9, 10, 14, 13,  7, 15,  4,  8,  3,  5,  2,  6, 12])

In [75]:
np.sort(nf)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [77]:
nf.sort()
nf

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [79]:
nong = np.random.randint(16, size=(4,4))
nong

array([[ 7, 15,  8,  4],
       [11, 10,  2, 11],
       [ 5,  8,  6, 11],
       [12, 12,  1,  3]])

In [80]:
np.sort(nong)

array([[ 4,  7,  8, 15],
       [ 2, 10, 11, 11],
       [ 5,  6,  8, 11],
       [ 1,  3, 12, 12]])

In [81]:
np.sort(nong, axis=0)

array([[ 5,  8,  1,  3],
       [ 7, 10,  2,  4],
       [11, 12,  6, 11],
       [12, 15,  8, 11]])

* 总结:axis含义为沿着，某个方向不在，对该方向的值遍历，在每个该方向垂直方向进行目标操作。所以堆叠axis=0,x方向不变，y方向垂直堆叠
    
sum,x=0时求的是x方向上每一列的和， sort，x为0时，求的时x方向每一列的排序

In [91]:
np.random.shuffle(nf)
nf

array([ 9, 10,  6,  8,  1, 15,  7,  2,  4, 14,  5, 13,  3,  0, 12, 11])

* argsort:从小到大数据在元数据的索引

In [85]:
np.argsort(nf)

array([ 7, 11, 14, 13,  9,  6,  3,  4,  5, 10, 15,  2,  0,  1,  8, 12],
      dtype=int64)

In [93]:
np.partition(nf, 8)

array([ 2,  1,  3,  0,  4,  6,  5,  7,  8,  9, 14, 13, 10, 15, 12, 11])

In [92]:
np.argpartition(nf, 8)

array([ 7,  4, 12, 13,  8,  2, 10,  6,  3,  0,  9, 11,  1,  5, 14, 15],
      dtype=int64)

In [94]:
nong

array([[ 7, 15,  8,  4],
       [11, 10,  2, 11],
       [ 5,  8,  6, 11],
       [12, 12,  1,  3]])

In [95]:
np.argsort(nong,axis=1)

array([[3, 0, 2, 1],
       [2, 1, 0, 3],
       [0, 2, 1, 3],
       [2, 3, 0, 1]], dtype=int64)