# Numpy矩阵运算

给定一个向量，让向量中的每一个数乘以2

a = (0,1,2)

a * 2= (0,2,4) 

## python原生方法

In [1]:
ap = [x for x in range(1000000)]

In [2]:
%%time
ap2 = [x*2 for x in ap]


Wall time: 94.2 ms


## numpy方法

In [3]:
import numpy as np

In [4]:
an = np.arange(1000000)

In [5]:
%%time
an22 = 2 * an

Wall time: 1.98 ms


In [6]:
2 * np.arange(10)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Universal Function

In [7]:
l = np.arange(1,16).reshape((3,5))
l

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [8]:
l+1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [9]:
l-1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
3 ** l

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [11]:
np.exp(l)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [12]:
np.power(3,l)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [13]:
np.log(l)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [14]:
np.log2(l)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [15]:
np.log10(l)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

## 矩阵运算

In [16]:
A = np.arange(4).reshape(2,-1)
A

array([[0, 1],
       [2, 3]])

In [17]:
B = np.full((2,2),10)
B

array([[10, 10],
       [10, 10]])

In [18]:
A + B

array([[10, 11],
       [12, 13]])

In [19]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [20]:
A * B

array([[ 0, 10],
       [20, 30]])

In [21]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [22]:
A.T

array([[0, 2],
       [1, 3]])

## 向量矩阵运算

In [23]:
v = np.array([1,2])

In [24]:
A + v

array([[1, 3],
       [3, 5]])

In [25]:
A + np.vstack([v]*A.shape[0])

array([[1, 3],
       [3, 5]])

In [26]:
A + np.tile(v,(A.shape[0],1))

array([[1, 3],
       [3, 5]])

In [27]:
v * A

array([[0, 2],
       [2, 6]])

In [28]:
A * v

array([[0, 2],
       [2, 6]])

In [29]:
v.dot(A)

array([4, 7])

In [30]:
A.dot(v).T

array([2, 8])

* numpy自动行向量、列向量处理和转换

## 矩阵的逆

* 概念，与原矩阵相乘得到单位矩阵

In [31]:
AI = np.linalg.inv(A)

In [32]:
A.dot(AI)

array([[1., 0.],
       [0., 1.]])

In [33]:
E = np.arange(16).reshape((2,8))

In [34]:
E

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

* 伪逆矩阵：原矩阵右乘伪逆矩阵为单位矩阵

In [35]:
EI = np.linalg.pinv(E)

In [36]:
EI

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -1.04083409e-17],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [37]:
E.dot(EI)

array([[ 1.00000000e+00, -2.49800181e-16],
       [ 0.00000000e+00,  1.00000000e+00]])

In [38]:
EI.dot(E)

array([[ 4.16666667e-01,  3.33333333e-01,  2.50000000e-01,
         1.66666667e-01,  8.33333333e-02,  3.05311332e-16,
        -8.33333333e-02, -1.66666667e-01],
       [ 3.33333333e-01,  2.73809524e-01,  2.14285714e-01,
         1.54761905e-01,  9.52380952e-02,  3.57142857e-02,
        -2.38095238e-02, -8.33333333e-02],
       [ 2.50000000e-01,  2.14285714e-01,  1.78571429e-01,
         1.42857143e-01,  1.07142857e-01,  7.14285714e-02,
         3.57142857e-02,  2.22044605e-16],
       [ 1.66666667e-01,  1.54761905e-01,  1.42857143e-01,
         1.30952381e-01,  1.19047619e-01,  1.07142857e-01,
         9.52380952e-02,  8.33333333e-02],
       [ 8.33333333e-02,  9.52380952e-02,  1.07142857e-01,
         1.19047619e-01,  1.30952381e-01,  1.42857143e-01,
         1.54761905e-01,  1.66666667e-01],
       [-8.32667268e-17,  3.57142857e-02,  7.14285714e-02,
         1.07142857e-01,  1.42857143e-01,  1.78571429e-01,
         2.14285714e-01,  2.50000000e-01],
       [-8.33333333e-02, -2.380952