# Numpy

## Numpy.array(数组和矩阵)

In [1]:
import numpy as np
import array

In [2]:
np.__version__

'1.16.2'

### 使用[]生成numpy.array

In [3]:
arr = array.array("i", [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
nparr2 = np.array([1, 2.3, 3])
nparr2.dtype

dtype('float64')

### 其他生成numpy.array的方式

In [6]:
zeroArr = np.zeros(10)
zeroArr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
intZeroArr = np.zeros(10, dtype=int)
intZeroArr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.zeros(shape=(3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [10]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.full(shape=(3,5), fill_value=666.0)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

### arange

In [12]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [13]:
np.arange(0, 20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
np.arange(0,1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

### linspace(起始点(包括)，终止点（包括），元素个数)

In [15]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [16]:
np.random.randint(10)

9

In [17]:
np.random.randint(1,10, size=10)

array([7, 3, 4, 6, 6, 9, 5, 8, 7, 2])

In [18]:
np.random.randint(1,10, size=(3,5))

array([[4, 4, 6, 1, 8],
       [4, 3, 1, 9, 5],
       [8, 8, 1, 1, 2]])

In [19]:
np.random.seed(123)

In [20]:
np.random.randint(1,10, size=(3,5))

array([[3, 3, 7, 2, 4],
       [7, 2, 1, 2, 1],
       [1, 4, 5, 1, 1]])

In [21]:
np.random.randint(1,10, size=(3,5))

array([[5, 2, 8, 4, 3],
       [5, 8, 3, 5, 9],
       [1, 8, 4, 5, 7]])

### random方法生成0-1之间的均匀的随机数

In [22]:
np.random.random(10)

array([0.32295891, 0.36178866, 0.22826323, 0.29371405, 0.63097612,
       0.09210494, 0.43370117, 0.43086276, 0.4936851 , 0.42583029])

### normal方法生成符合均值均值为0, 方差为1的正态分布的随机数

In [23]:
np.random.normal()

-0.6959811757511152

In [24]:
np.random.normal(10)

8.225865940299622

In [25]:
np.random.normal(10, 10)

33.61601261344558

In [26]:
np.random.normal(0, 1, 5)

array([ 0.03499308, -0.34464169, -0.72503229,  1.03960617, -0.24172804])

In [27]:
np.random.normal(0, 1, (3,5))

array([[-0.11290536, -1.66069578,  0.01353855,  0.33737412, -0.92662298],
       [ 0.27574741,  0.37085233,  1.17430715, -2.03229248,  0.58250829],
       [-0.7211758 , -1.7024236 ,  0.76764147,  0.37067905,  2.07545935]])

In [28]:
x = np.arange(10)

In [29]:
X = np.arange(15).reshape((3,5))

In [30]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
x.ndim

1

In [33]:
X.ndim

2

In [34]:
x.shape

(10,)

In [35]:
X.shape

(3, 5)

In [36]:
x.size

10

In [37]:
X.size

15

### npmy.array数据访问

In [38]:
X[(1,2)]

7

In [39]:
X[1,2]

7

In [40]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [41]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [42]:
X[:,0]

array([ 0,  5, 10])

### numpy子矩阵是父矩阵的引用,赋值相互影响，python原生数组切片产生的子数组是全新的数组，赋值没有影响

In [43]:
subX = X[:2,:3].copy()

In [44]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [45]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
x.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 合并操作

In [47]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [48]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [49]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8,9],
             [10,11,12]])

In [50]:
np.concatenate([A, B])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [67]:
np.concatenate([A,B], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [52]:
np.vstack([A,B])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### 分割操作

In [53]:
Y = np.arange(10)

In [54]:
x1,x2 = np.split(Y, [3])

In [55]:
x2

array([3, 4, 5, 6, 7, 8, 9])

In [56]:
Y2 = np.arange(16).reshape((4,-1))

In [57]:
x3,x4 = np.split(Y2, [2])

In [58]:
x3

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [59]:
x5,x6 = np.split(Y2, [2], axis=1)

In [60]:
x5

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [61]:
Y2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
x7,x8 = np.hsplit(Y2,[-1])

In [63]:
x8

array([[ 3],
       [ 7],
       [11],
       [15]])

### numpy切片表达式如果一个方向固定,另一个方向是个范围,得到的结果将是一个向量

In [64]:
Y2[:,2]

array([ 2,  6, 10, 14])

In [65]:
x8[:,0]

array([ 3,  7, 11, 15])